DEFINE_ACTION_FUNCTION "BLIND_FIGHT"
BEGIN
	LAF "GT_ADD_SPELL"
	INT_VAR
		"type" = 3
	STR_VAR
		"idsName" = "INNATE_BLIND_FIGHT"
	RET
		"INNATE_BLIND_FIGHT" = "resName"
	END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "INNATE_BLIND_FIGHT"
		COPY "cdtweaks\luke\bam\innate\blind_fight.bam" "override\%INNATE_BLIND_FIGHT%d.bam"
	END
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "%INNATE_BLIND_FIGHT%D" RET "feedback_icon" = "index" END
		// Listener: run 'func' each time a sprite has finished evaluating its effects
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Innate Abilities" "sourceFileSpec" = "cdtweaks\luke\lua\innate\blind_fight.lua" "destRes" = "m_gtspin" END
		//
		ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
			COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
		END
	END
END