/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// BG Casting Graphics                              \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_map_casting BEGIN
  abjurcg => cgabjura // abjuration
  altercg => cgaltera // alteration
  conjucg => cgconjur // conjuration
  divincg => cgdivina // divination
  enchacg => cgenchan // enchantment
  illuscg => cgillusi // illusion
  invoccg => cginvoca // invocation
  necrocg => cgnecrom // necromancy
END

ACTION_IF enhanced_edition THEN BEGIN

  ACTION_PHP_EACH cd_map_casting AS iwd => bg2 BEGIN

    COPY ~cdtweaks/bam/%iwd%_ee.bam~ ~override/%iwd%.bam~
         ~cdtweaks/bam/%iwd%_ee.bam~ ~override/%bg2%.bam~ // iwdee has extra unused set, but replace anyway
    COPY ~cdtweaks/pro/cast_bg.pro~  ~override/%bg2%.pro~
      WRITE_ASCIIE 0x104 ~%iwd%~ #8

  END

END ELSE BEGIN

  ACTION_IF game_is_iwd-in-bg2 THEN BEGIN

    ACTION_PHP_EACH cd_map_casting AS iwd => bg2 BEGIN

      COPY ~cdtweaks/bam/%iwd%.bam~ ~override/%bg2%.bam~

    END

  END ELSE BEGIN // original iwd

    ACTION_PHP_EACH cd_map_casting AS iwd => bg2 BEGIN

      COPY ~cdtweaks/bam/%iwd%.bam~ ~override~

    END

  END

END

LAF HANDLE_AUDIO STR_VAR audio_path = ~cdtweaks/wav/casting_bg~ oggdec_path = ~cdtweaks/wav~ END
