/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                            \\\\\
///// Outline White Spell Icons for Accessibility                \\\\\
/////                                                            \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

/////                                                            \\\\\
///// add gray outline                                           \\\\\
/////                                                            \\\\\

OUTER_SPRINT bam_outline spell_gray
INCLUDE ~cdtweaks/lib/outline_icons.tpa~


/*
the rest of this is leftover code to make BAMs from the re-colored PNGs


ACTION_FOR_EACH file IN
// bg2ee
  sppr104 sppr205 sppr303 sppr309 sppr312 sppr318 sppr415 sppr611 sppr706 sppr711
  spwi107 spwi109 spwi110 spwi111 spwi123 spwi202 spwi203 spwi204 spwi207 spwi208
  spwi209 spwi214 spwi216 spwi224 spwi301 spwi302 spwi305 spwi306 spwi322 spwi326
  spwi402 spwi410 spwi413 spwi416 spwi420 spwi421 spwi424 spwi425 spwi505 spwi515
  spwi603 spwi607 spwi609 spwi613 spwi617 spwi703 spwi710 spwi722 spwi804 spwi809
  spwi908 spwi916 spwi919

  // no sppr312 sppr711 spwi107 spwi123 spwi204 spwi209 spwi214 spwi216 spwi224
  //    spwi305 spwi410 spwi603 spwi613
  //sppr209 sppr321 spwi528
BEGIN

  COPY ~weidu_external\cdtweaks\bam_working\%file%c.bamd~ ~weidu_external\cdtweaks\bam_working\%file%c.bamd~
    REPLACE_TEXTUALLY ~weidu_external/cdtweaks/bam_working/~ ~~

  DELETE ~weidu_external/cdtweaks/bam_working/%file%c.bam~

  AT_NOW ~.\weidu_external\cdtweaks\bam_working\bammer.exe -input weidu_external\cdtweaks\bam_working\%file%c.bamd -output weidu_external\cdtweaks\bam_working\%file%c.bam~

END
*/
