DEFINE_ACTION_FUNCTION "DEFENSIVE_ROLL"
BEGIN
	WITH_SCOPE BEGIN
		OUTER_SET "feedback_strref" = RESOLVE_STR_REF (@0)
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Functions to be invoked via op403" "sourceFileSpec" = "cdtweaks\luke\lua\defensive_roll.lua" "destRes" = "m_gt#403" END
	END
	// Listener: run 'func' each time a sprite has finished evaluating its effects
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Listeners" "sourceFileSpec" = "cdtweaks\luke\lua\defensive_roll_apply.lua" "destRes" = "m_gtlstn" END
END