DEFINE_ACTION_FUNCTION "DISARM"
BEGIN
	LAF "GT_ADD_SPELL"
	INT_VAR
		"level" = 4
		"preferredSlot" = 44
		"type" = 4
	STR_VAR
		"idsName" = "THIEF_DISARM"
	RET
		"THIEF_DISARM" = "resName"
	END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "THIEF_DISARM"
		// Disarm (main spl file)
		CREATE "spl" "%THIEF_DISARM%"
		COPY_EXISTING "%THIEF_DISARM%.spl" "override"
			WRITE_LONG NAME1 RESOLVE_STR_REF (@0)
			WRITE_LONG NAME2 "-1"
			WRITE_LONG UNIDENTIFIED_DESC RESOLVE_STR_REF (@1)
			WRITE_LONG DESC "-1"
			WRITE_LONG 0x18 (BIT14 BOR BIT25) // ignore dead/wild magic, castable when silenced
			WRITE_SHORT 0x1C 4 // innate
			WRITE_LONG 0x34 1 // level
			WRITE_ASCII 0x3A "%DEST_RES%B" #8 // icon
			//
			LPF "ADD_SPELL_HEADER" INT_VAR "range" = 0 STR_VAR "icon" = "%DEST_RES%B" END
			//
			LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 138 "target" = 1 "parameter2" = 0 END // SEQ_ATTACK
		BUT_ONLY
		// icon
		COPY "cdtweaks\luke\bam\class\disarm.bam" "override\%THIEF_DISARM%b.bam"
	END
	// lua
	WITH_SCOPE BEGIN
		OUTER_SET "feedback_strref_disarm" = RESOLVE_STR_REF (@0)
		OUTER_SET "feedback_strref_inventory_full" = RESOLVE_STR_REF (@101)
		OUTER_SET "feedback_strref_hit" = RESOLVE_STR_REF (@102)
		OUTER_SET "feedback_strref_miss" = RESOLVE_STR_REF (@103)
		OUTER_SET "feedback_strref_melee_only" = RESOLVE_STR_REF (@104)
		OUTER_SET "feedback_strref_cannot_be_disarmed" = RESOLVE_STR_REF (@105)
		OUTER_SET "feedback_strref_weapon_ineffective" = RESOLVE_STR_REF (@106)
		//
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Class/Kit Abilities" "sourceFileSpec" = "cdtweaks\luke\lua\class\disarm.lua" "destRes" = "m_gtspcl" END
		//
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Utility Functions / Listeners" "sourceFileSpec" = "cdtweaks\luke\lua\utility\damage_type.lua" "destRes" = "m_gtutil" END
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Utility Functions / Listeners" "sourceFileSpec" = "cdtweaks\luke\lua\utility\display_sprite_message.lua" "destRes" = "m_gtutil" END
	END
	//
	ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
		COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
	END
END