DEFINE_ACTION_FUNCTION "DIVINE_GRACE_DARK_BLESSING"
BEGIN
	ACTION_IF !(FILE_EXISTS_IN_GAME "gtdvngrc.bam") BEGIN
		COPY "cdtweaks\bam\gtdvngrc.bam" "override"
	END
	ACTION_IF !(FILE_EXISTS_IN_GAME "gtdrkbls.bam") BEGIN
		COPY "cdtweaks\bam\gtdrkbls.bam" "override"
	END
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "gtdvngrc" RET "feedback_icon_paladin" = "index" END
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@1) STR_VAR "bam_file" = "gtdrkbls" RET "feedback_icon_blackguard" = "index" END
		// Listener: run 'func' each time a sprite has finished evaluating its effects
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Listeners" "sourceFileSpec" = "cdtweaks\luke\lua\divine_grace.lua" "destRes" = "m_gtlstn" END
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Listeners" "sourceFileSpec" = "cdtweaks\luke\lua\dark_blessing.lua" "destRes" = "m_gtlstn" END
		//
		ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
			COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
		END
	END
END