DEFINE_ACTION_FUNCTION "DUAL_WIELD"
BEGIN
	WITH_SCOPE BEGIN
		ACTION_IF !(FILE_EXISTS_IN_GAME "gtmharmr.bam") BEGIN
			COPY "cdtweaks\bam\gtmharmr.bam" "override"
		END
	END
	//
	<<<<<<<< .../cdtweaks-inlined/empty
	>>>>>>>>
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "gtmharmr" RET "feedback_icon" = "index" END
		// Listener: run 'func' each time a sprite has finished evaluating its effects
		ACTION_IF !(FILE_EXISTS_IN_GAME "m_gtlstn.lua") BEGIN
			COPY ".../cdtweaks-inlined/empty" "override\m_gtlstn.lua"
				DELETE_BYTES 0x0 BUFFER_LENGTH
				INSERT_BYTES 0x0 STRING_LENGTH "-- Listeners --%WNL%%WNL%"
				WRITE_ASCII 0x0 "-- Listeners --%WNL%%WNL%"
			BUT_ONLY_IF_IT_CHANGES
		END
		COPY_EXISTING "m_gtlstn.lua" "override"
			APPEND_FILE_EVALUATE TEXT "cdtweaks\luke\lua\dual_wield.lua"
		BUT_ONLY UNLESS "cdtweaksDualWield"
		//
		ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
			COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
		END
	END
END