DEFINE_ACTION_FUNCTION "FEARLESS"
BEGIN
	WITH_SCOPE BEGIN
		COPY "cdtweaks\bam\cdhlfrls.bam" "override"
	END
	//
	LAF "ADD_EXTENDED_STAT" INT_VAR "max" = 20 STR_VAR "identifier" = "GT_IMMUNITY" END
	//
	WITH_SCOPE BEGIN
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "cdhlfrls" RET "feedback_icon" = "index" END
		// Listener: run 'func' each time a sprite has finished evaluating its effects
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Listeners" "sourceFileSpec" = "cdtweaks\luke\lua\fearless_apply.lua" "destRes" = "m_gtlstn" END
	END
	//
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Functions to be invoked via op403" "sourceFileSpec" = "cdtweaks\luke\lua\fearless.lua" "destRes" = "m_gt#403" END
	//
	ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
		COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
	END
END