ACTION_IF tutu_gen BEGIN
  INCLUDE ~cdtweaks/lib/inns_jk_fix.tpa~
END 

<<<<<<<< ./inline/inn_data.2da
npc      state_tutu  state_tutu2   state_bgt state_bgt2           state_ee      state_ee2       dmwwresponse         beregost_xloc   beregost_yloc    friendly_xloc  friendly_yloc   nashkel_xloc   nashkel_yloc   elfsong_xloc   elfsong_yloc postdialogue
AJANTIS  0           -1            0         -1                   0             -1              20810                824             961              766            966             602            463            537            704          lookitup
SUFINCH  3           -1            3         -1                   3             -1              20840                818             970              800            980             590            448            568            717          SUFINCHP
IMOEN    0           -1            18        -1                   2             -1              20811                812             980              814            1006            573            436            598            737          lookitup
A#MURN   1           -1            1         -1                   1             -1              20841                806             990              760            900             453            433            630            730          A#MURNP
KAGAIN   0           -1            2         -1                   2             -1              20812                800             1000             721            790             247            431            661            726          lookitup
J#INDI01 0           -1            0         -1                   0             -1              20842                749             1010             740            768             264            444            677            694          J#IndiP
EDWIN    0           -1            9         -1                   0             -1              20813                788             1020             778            754             284            454            692            664          lookitup
BRANWEN  0           -1            0         -1                   0             -1              20814                776             1040             479            634             461            394            637            621          lookitup
SAFANA   0           -1            2         -1                   2             -1              20815                764             1060             523            595             429            411            783            732          lookitup
GARRICK  0           -1            2         -1                   2             -1              20816                752             1080             575            562             367            580            837            783          lookitup
CORAN    0           -1            0         -1                   0             -1              20817                740             1100             614            521             402            613            772            853          lookitup
KIVAN    0           -1            2         -1                   2             -1              20818                730             1128             1070           663             260            307            686            843          lookitup
YESLICK  0           -1            0         -1                   0             -1              20819                820             1110             1117           697             251            351            653            782          lookitup
XAN      0           -1            2         -1                   2             -1              20820                860             965              1178           738             531            392            702            736          lookitup
ALORA    0           -1            0         -1                   0             -1              20821                850             985              1224           761             525            428            806            455          lookitup
FALDORN  0           -1            0         -1                   0             -1              20822                840             1005             817            720             448            423            823            517          lookitup
QUAYLE   0           -1            2         -1                   2             -1              20823                830             1025             802            686             440            473            875            538          lookitup
SHARTEEL 0           -1            2         -1                   2             -1              20824                820             1045             880            745             515            550            921            525          lookitup
TIAX     0           -1            2         -1                   2             -1              20825                810             1065             939            718             480            525            1004           605          lookitup
VICONIA  0           -1            16        -1                   2             -1              20826                800             1085             789            759             444            505            745            674          lookitup
JAHEIRA  0           1             78        79                   4              5              20831                790             1105             701            903             669            161            440            713          lookitup
KHALID   0           1             4         5                    4              5              20832                806             1138             726            924             729            199            471            690          lookitup
DYNAHEIR 0           1             4         5                    4              5              20833                894             970              316            611             850            277            595            476          lookitup
MINSC    0           1             14        15                   4              5              20834                882             990              356            641             839            318            617            507          lookitup
XZAR     0           1             4         5                    4              5              20835                870             1010             682            684             747            362            692            421          lookitup
MONTARON 0           1             4         5                    4              5              20836                855             1030             667            725             706            396            734            397          lookitup
SKIE     0           1             4         5                    4              5              20837                846             1050             571            428             583            260            822            355          lookitup
ELDOTH   0           1             4         5                    4              5              20838                834             1070             621            466             525            278            873            377          lookitup
NEERA    -1          -1            -1        -1                   1             -1              20841                756             1156             669            421             181            406            878            568          lookitup
DORN     -1          -1            -1        -1                   0             -1              20842                789             1155             755            419             371            424            939            607          lookitup
RASAAD   -1          -1            -1        -1                   0             -1              20843                701             1038             1088           757             629            475            981            645          lookitup
>>>>>>>>

ACTION_IF ((game_is_bgt) AND (!MOD_IS_INSTALLED ~cdtweaks/setup-cdtweaks.tp2~ ~4025~)) BEGIN
  COMPILE EVALUATE_BUFFER ~cdtweaks/dlg/depart_bgt.d~
END

ACTION_IF enhanced_edition BEGIN
  COMPILE EVALUATE_BUFFER ~cdtweaks/dlg/depart_ee.d~ // do this early, otherwise might erase neera's new action move to FAI
END

COPY ~./inline/inn_data.2da~ ~./inline/inn_data.2da~
  COUNT_2DA_ROWS 17 row_count
  FOR (row = 1 ; row < row_count ; ++row) BEGIN
    FOR (col = 0 ; col < 17 ; ++col) BEGIN
      READ_2DA_ENTRY 0   col 17 var
      READ_2DA_ENTRY row col 17 val
      SPRINT ~%var%~ ~%val%~ // use column header as variable name
    END
    PATCH_IF enhanced_edition BEGIN
      SPRINT state1 ~%state_ee%~
      SPRINT state2 ~%state_ee2%~
    END ELSE BEGIN
      PATCH_IF game_is_bgt BEGIN
        SPRINT state1 ~%state_bgt%~
        SPRINT state2 ~%state_bgt2%~
      END ELSE BEGIN
        SPRINT state1 ~%state_tutu%~
        SPRINT state2 ~%state_tutu2%~
      END
    END
    INNER_ACTION BEGIN

      ACTION_IF ("%postdialogue%" STRING_COMPARE_CASE "lookitup" = 0) BEGIN
        OUTER_SPRINT ~postdialogue~ EVALUATE_BUFFER ~%%npc%_POST%~
      END

      ACTION_IF ("%npc%" STRING_COMPARE_CASE "IMOEN" = 0) BEGIN
        OUTER_SPRINT npc ~%IMOEN_DV%~
      END

      ACTION_IF FILE_EXISTS_IN_GAME ~%postdialogue%.dlg~ BEGIN

        ACTION_IF state2 < 0 BEGIN OUTER_SPRINT state2 ~~ END
        COPY ~cdtweaks/dlg/depart.d~ ~weidu_external/cdtweaks/depart_%npc%.d~

        COMPILE EVALUATE_BUFFER ~weidu_external/cdtweaks/depart_%npc%.d~

      END // dialogue check

    END // inner_action
  END // row loop
  BUT_ONLY

ACTION_IF enhanced_edition BEGIN

  ACTION_IF game_is_eet BEGIN
    STRING_SET 228125 @20844 // remove the part about Neera going to FAI
    STRING_SET 228392 @20845 // remove the part about Dorn going to FAI
    STRING_SET 229019 @20846 // remove the part about Rasaad going to Nashkel
    OUTER_SET baelothreply = 231931
  END ELSE BEGIN
    STRING_SET 28125 @20844 // remove the part about Neera going to FAI
    STRING_SET 28392 @20845 // remove the part about Dorn going to FAI
    STRING_SET 29019 @20846 // remove the part about Rasaad going to Nashkel
    OUTER_SET baelothreply = 31931
  END

  // handle Baeloth here, since he's a special case regardless
  //COPY ~cdtweaks/dlg/depart_ee.d~ ~weidu_external/cdtweaks/dlg/depart_ee.d~ EVALUATE_BUFFER
  COMPILE EVALUATE_BUFFER ~cdtweaks/dlg/depart_baeloth.d~

  // neera has additional scripting to bail
  COPY_EXISTING ~neera%eet_var%.bcs~ ~override~
    DECOMPILE_AND_PATCH BEGIN
      REPLACE_TEXTUALLY ~\(!InPartyAllowDead("NEERA")[ %TAB%%LNL%%MNL%%WNL%]+Global("AdoyLeft","OH2010",3)\)~ ~False() \1~
      REPLACE_TEXTUALLY ~\(!\(I[fs]ValidForPartyDialog\(ue\)?\|InParty\)("NEERA")[ %TAB%%LNL%%MNL%%WNL%]+Global("NEERA_START","GLOBAL",1)\)~ ~False() \1~ // with more banters, may decompile as IVFPD
    END
    BUT_ONLY

  // as does rasaad
  COPY_EXISTING ~rasaad%eet_var%.bcs~ ~override~
    DECOMPILE_AND_PATCH BEGIN
      REPLACE_TEXTUALLY ~\(!\(I[fs]ValidForPartyDialog\(ue\)?\|InParty\)(Myself)[ %TAB%%LNL%%MNL%%WNL%]+ActionListEmpty()[ %TAB%%LNL%%MNL%%WNL%]+Global("RASAAD_IN_PARTY","GLOBAL",0)\)~ ~False() \1~ // with more banters, may decompile as IVFPD
      REPLACE_TEXTUALLY ~\(!\(I[fs]ValidForPartyDialog\(ue\)?\|InParty\)(Myself)[ %TAB%%LNL%%MNL%%WNL%]+ActionListEmpty()[ %TAB%%LNL%%MNL%%WNL%]+Global("GAMAZ_DEFEATED","GLOBAL",2)\)~  ~False() \1~ // with more banters, may decompile as IVFPD
    END
    BUT_ONLY

END

