DEFINE_ACTION_FUNCTION "NATURE_SENSE"
BEGIN
	LAF "GT_ADD_SPELL"
	INT_VAR
		"level" = 6
		"type" = 4
	STR_VAR
		"idsName" = "DRUID_NATURE_SENSE"
	RET
		"DRUID_NATURE_SENSE" = "resName"
	END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "DRUID_NATURE_SENSE"
		//
		COPY "cdtweaks\luke\bam\class\nature_sense.bam" "override\%DRUID_NATURE_SENSE%d.bam" // courtesy of zenblack
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@0) STR_VAR "bam_file" = "%DRUID_NATURE_SENSE%d" RET "feedback_icon" = "index" END
		//
		ACTION_TO_UPPER "DRUID_NATURE_SENSE"
		//
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Class/Kit Abilities" "sourceFileSpec" = "cdtweaks\luke\lua\class\nature_sense.lua" "destRes" = "m_gtspcl" END
	END
END