DEFINE_ACTION_FUNCTION "SPELLCRAFT_COUNTERSPELL"
BEGIN
	LAF "GT_ADD_SPELL"
	STR_VAR
		"idsName" = "INNATE_COUNTERSPELL"
	RET
		"INNATE_COUNTERSPELL" = "resName"
	END
	//
	LAF "ADD_EXTENDED_STAT" INT_VAR "max" = 25 STR_VAR "identifier" = "GT_IGNORE_ACTION_ADD_SPRITE_STARTED_ACTION_LISTENER" END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "INNATE_COUNTERSPELL"
		//
		ACTION_CLEAR_ARRAY "cdtweaks_counterspell"
		ACTION_DEFINE_ASSOCIATIVE_ARRAY "cdtweaks_counterspell" BEGIN
			// mschool, casting sound => casting animation
			1, "a", "CAS_M02" => 12 // ABJURER
			2, "b", "CAS_M03" => 14 // CONJURER
			3, "c", "CAS_M04" => 16 // DIVINER
			4, "d", "CAS_M05" => 11 // ENCHANTER
			5, "e", "CAS_M01" => 13 // ILLUSIONIST
			6, "f", "CAS_M06" => 15 // INVOKER
			7, "g", "CAS_M07" => 9 // NECROMANCER
			8, "h", "CAS_M08" => 10 // TRANSMUTER
		END
		//
		ACTION_PHP_EACH "cdtweaks_counterspell" AS "key" => "value" BEGIN
			CREATE "spl" "%INNATE_COUNTERSPELL%%key_1%"
			COPY_EXISTING "%INNATE_COUNTERSPELL%%key_1%.spl" "override"
				WRITE_LONG NAME1 RESOLVE_STR_REF ((AT "%key%"))
				WRITE_LONG UNIDENTIFIED_DESC "-1"
				WRITE_LONG 0x18 (BIT9 BOR BIT10) // break sanctuary/invisibility
				WRITE_SHORT 0x1C 4 // type: innate
				WRITE_LONG 0x34 1 // level
				WRITE_SHORT 0x22 "%value%" // casting animation
				WRITE_BYTE 0x25 "%key%" // mschool
				WRITE_ASCII 0x10 "%key_2%" #8 // casting sound
				//
				LPF "ADD_SPELL_HEADER" INT_VAR "range" = 30 END
				//
				LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 402 "target" = 2 "parameter1" = 3 STR_VAR "resource" = "%INNATE_COUNTERSPELL%" END // invoke lua
			BUT_ONLY
		END
	END
	//
	WITH_SCOPE BEGIN
		ACTION_TO_LOWER "INNATE_COUNTERSPELL"
		//
		LAF "ADD_STATDESC_ENTRY" INT_VAR "description" = RESOLVE_STR_REF (@100) STR_VAR "bam_file" = "%INNATE_COUNTERSPELL%d" RET "feedback_icon" = "index" END
		//
		COPY "cdtweaks\luke\bam\spellcraft_counterspell\portrait_icon.bam" "override\%INNATE_COUNTERSPELL%d.bam"
		COPY "cdtweaks\luke\bam\spellcraft_counterspell\spl_icon.bam" "override\%INNATE_COUNTERSPELL%b.bam"
		//
		CREATE "spl" "%INNATE_COUNTERSPELL%y"
		COPY_EXISTING "%INNATE_COUNTERSPELL%y.spl" "override"
			WRITE_LONG NAME1 RESOLVE_STR_REF (@101)
			WRITE_LONG UNIDENTIFIED_DESC "-1"
			WRITE_LONG 0x18 (BIT9 BOR BIT10 BOR BIT14) // break sanctuary/invisibility, ignore dead/wild magic
			WRITE_SHORT 0x1C 4 // type: innate
			WRITE_LONG 0x34 1 // level
			WRITE_ASCII 0x3A "%INNATE_COUNTERSPELL%b" #8 // icon
			//
			LPF "ADD_SPELL_HEADER" INT_VAR "target" = 5 "range" = 30 STR_VAR "icon" = "%INNATE_COUNTERSPELL%b" END
			//
			LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 138 "target" = 1 "parameter2" = 7 END // SEQ_READY
			LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 321 "target" = 1 "timing" = 1 STR_VAR "resource" = "%DEST_RES%" END // remove effects by resource
			LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 172 "target" = 1 "timing" = 1 STR_VAR "resource" = "%DEST_RES%" END // remove spell
			LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 139 "target" = 1 "parameter1" = RESOLVE_STR_REF (@102) "timing" = 1 END // feedback string
			LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 142 "target" = 1 "parameter2" = "%feedback_icon%" "timing" = 1 END // feedback icon
			LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 402 "target" = 1 "parameter1" = 1 STR_VAR "resource" = "%INNATE_COUNTERSPELL%" END // invoke lua
		BUT_ONLY
		//
		CREATE "spl" "%INNATE_COUNTERSPELL%z"
		COPY_EXISTING "%INNATE_COUNTERSPELL%z.spl" "override"
			WRITE_LONG NAME1 RESOLVE_STR_REF (@103)
			WRITE_LONG UNIDENTIFIED_DESC "-1"
			WRITE_LONG 0x18 (BIT9 BOR BIT10 BOR BIT14) // break sanctuary/invisibility, ignore dead/wild magic
			WRITE_SHORT 0x1C 4 // type: innate
			WRITE_LONG 0x34 1 // level
			WRITE_ASCII 0x3A "%INNATE_COUNTERSPELL%b" #8
			//
			LPF "ADD_SPELL_HEADER" INT_VAR "target" = 5 "range" = 30 STR_VAR "icon" = "%INNATE_COUNTERSPELL%b" END
			//
			LPF "ADD_SPELL_EFFECT" INT_VAR "opcode" = 402 "target" = 1 "parameter1" = 2 STR_VAR "resource" = "%INNATE_COUNTERSPELL%" END // invoke lua
		BUT_ONLY
	END
	// lua
	WITH_SCOPE BEGIN
		OUTER_SET "feedback_strref_spellcraft" = RESOLVE_STR_REF (@200)
		OUTER_SET "feedback_strref_isCasting" = RESOLVE_STR_REF (@201)
		//
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Spellcraft / Counterspell class feat for spellcasters" "sourceFileSpec" = "cdtweaks\luke\lua\spellcraft_counterspell\utility.lua" "destRes" = "m_gtctsp" END
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Spellcraft / Counterspell class feat for spellcasters" "sourceFileSpec" = "cdtweaks\luke\lua\spellcraft_counterspell\gain_ability.lua" "destRes" = "m_gtctsp" END
		LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Spellcraft / Counterspell class feat for spellcasters" "sourceFileSpec" = "cdtweaks\luke\lua\spellcraft_counterspell\main.lua" "destRes" = "m_gtctsp" END
	END
	//
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Utility Functions / Listeners" "sourceFileSpec" = "cdtweaks\luke\lua\utility\decode_spell.lua" "destRes" = "m_gtutil" END
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Utility Functions / Listeners" "sourceFileSpec" = "cdtweaks\luke\lua\utility\effect_check.lua" "destRes" = "m_gtutil" END
	LAF "APPEND_LUA_FUNCTION" STR_VAR "description" = "Lua Tools" "sourceFileSpec" = "cdtweaks\luke\lua\tools\wrap_userdata.lua" "destRes" = "m_gttool" END
	//
	ACTION_IF !(FILE_EXISTS_IN_GAME "m_gttbls.lua") BEGIN
		COPY "cdtweaks\luke\lua\m_gttbls.lua" "override"
	END
END